name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MUAAZ_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Suppress Unsupported Compile SDK Warning
        run: echo "android.suppressUnsupportedCompileSdk=34" >> ./gradle.properties

      # Set up Mapbox Token
      - name: Set Mapbox Token
        run: echo "MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MUAAZ_SECRET }}" >> $GITHUB_ENV

      # Run Lint with Continue on Warning
      - name: Run lint with warning mode
        run: ./gradlew lint --continue --warning-mode all

      - name: Build with Gradle
        run: ./gradlew build --warning-mode all

      # Upload Build Artifacts
      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: APK Debug
          path: app/build/outputs/apk/debug/*.apk




